/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Button: typeof import('primevue/button')['default']
    CheckIcon: typeof import('@primeicons/vue/check')['default']
    DesktopIcon: typeof import('@primeicons/vue/desktop')['default']
    MoonIcon: typeof import('@primeicons/vue/moon')['default']
    SunIcon: typeof import('@primeicons/vue/sun')['default']
    Tag: typeof import('primevue/tag')['default']
    ThemeToggle: typeof import('./src/components/ThemeToggle.vue')['default']
    VerifyLicence: typeof import('./src/components/VerifyLicence.vue')['default']
  }
}
